### ISSUE TITLE
Enhancement Request: GZIP support (tar mode)

### ISSUE THREAD

**Issue by Pwntus** [replicate/pget#1]
Writing down how I implemented ZIP at first. As discussed, weights are not good for ZIP compression due to their "noisy" structure - decompressing with ZIP adds ~50-60 seconds.

1. Import `compress/gzip`.
2. When extracting, first create a uncompressed stream before feeding to the `tar` reader:

```go
func extractTarFile(buffer *bytes.Buffer, destDir string) error {
  uncompressedStream, err := gzip.NewReader(buffer)
  if err != nil {
    return err
  }

  tarReader := tar.NewReader(uncompressedStream)
  // ...
}
```

**Comment by tempusfrangit** [comment]
This should be much easier to implement now, do we want it?
