### ISSUE TITLE
Error: open /run/pget.pid: permission denied

### ISSUE THREAD

**Issue by yorickvP** [replicate/pget#128]
pget now requires root to run. Not very handy when testing.

$ pget version
Error: open /run/pget.pid: permission denied

$ sudo pget version
pget Version 0.5.4()

**Comment by nateraw** [comment]
Just ran into this myself when updating pget in this project: https://github.com/replicate/cog-huggingface-template/pull/15. Would be very very nice to not have to run as root every time.

**Comment by tempusfrangit** [comment]
There is a CLI option to change the pid path. But we should figure out a better place for the pid file if this is causing issues.

`--pid-file`; however the option is hidden from the help page. This should get you unblocked for now.

**Comment by yorickvP** [comment]
Maybe default to $XDG_RUNTIME_DIR if it's set?

**Comment by tempusfrangit** [comment]
@yorickvP want to contribute that fix? Happy to accept it.

**Comment by tempusfrangit** [comment]
Closing this issue. @yorickvP feel free to re-open and spin up a PR with the requested change.
