### ISSUE TITLE
Documentation: How to use pget to download AWS S3 object?

### ISSUE THREAD

**Issue by jby1993** [replicate/pget#16]
I've been trying for a long time to download a file from AWS S3 using pget, but haven't succeeded. Do you have an example of using pget to download files from AWS S3 or any instructions on AWS S3 configuration?

**Comment by mcam10** [comment]
@jby1993 still need this?

**Comment by mcam10** [comment]
Just did a test on this @tempusfrangit -- you will need to use the https scheme to the s3 object.. (assuming you have the correct bucket permissions setup)... wondering if its worth having pget read a users ~/.aws/config if it exists..

**Comment by jby1993** [comment]
Thank you for the reply, no need now.
