### ISSUE TITLE
pget cannot extract tar file generated on MacOS

### ISSUE THREAD

**Issue by simonpicard** [replicate/pget#166]
Hi team, many thanks for your great work.

I am using pget on replicate, deployed via cog.
When downloading a tar file via pget, I get the following error:
```
Error: error writing file: error extracting file: archive/tar: invalid tar header
```

The tar file I am attempting to extract has been created on MacOS via the following command:
```
tar -czvf my-folder.tar my-folder
```

The archive is then uploaded to AWS S3 and downloaded from there via pget.
The archive can be extracted without error on MacOS using the built-in extractor.

Could you please help me solve the issue?

**Comment by tempusfrangit** [comment]
This will be addressed by #183
